apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py-tyru-4556-oc 
  janus-idp.io/tekton: py-tyru-4556-oc
  backstage.io/kubernetes-id: py-tyru-4556-oc
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-tyru-4556-oc
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  